//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Photo { get; set; }
        public decimal Height { get; set; }
        public float Weight { get; set; }
        public Nullable<int> Grade_GradeId { get; set; }
        public string Address { get; set; }
        public Nullable<int> XepLoai { get; set; }
        public Nullable<int> HocLuc { get; set; }
        [JsonIgnore]

        public virtual Grade Grade { get; set; }
        [JsonIgnore]
        public virtual HocLuc HocLuc1 { get; set; }
        [JsonIgnore]
        public virtual XepLoai XepLoai1 { get; set; }
    }
}
