//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    public partial class BOMON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOMON()
        {
            this.GIAOVIENs = new HashSet<GIAOVIEN>();
        }
    
        public string MABM { get; set; }
        public string TENBM { get; set; }
        public string PHONG { get; set; }
        public string DIENTHOAI { get; set; }
        public string TRUONGBM { get; set; }
        public string MAKHOA { get; set; }
        public Nullable<System.DateTime> NGAYNHANCHUC { get; set; }
        [JsonIgnore]

        public virtual KHOA KHOA { get; set; }
        [JsonIgnore]

        public virtual GIAOVIEN GIAOVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        [JsonIgnore]
        public virtual ICollection<GIAOVIEN> GIAOVIENs { get; set; }
    }
}
