//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;    
    public partial class GIAOVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAOVIEN()
        {
            this.BOMONs = new HashSet<BOMON>();
            this.DETAIs = new HashSet<DETAI>();
            this.THAMGIADTs = new HashSet<THAMGIADT>();
            this.GIAOVIEN1 = new HashSet<GIAOVIEN>();
            this.KHOAs = new HashSet<KHOA>();
            this.NGUOITHANs = new HashSet<NGUOITHAN>();
        }
    
        public string MAGV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<double> LUONG { get; set; }
        public string PHAI { get; set; }
        public Nullable<System.DateTime> NGSINH { get; set; }
        public string DIACHI { get; set; }
        public string GVQLCM { get; set; }
        public string MABM { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMON> BOMONs { get; set; }
        [JsonIgnore]

        public virtual BOMON BOMON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<DETAI> DETAIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<THAMGIADT> THAMGIADTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<GIAOVIEN> GIAOVIEN1 { get; set; }
        [JsonIgnore]
        public virtual GIAOVIEN GIAOVIEN2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<KHOA> KHOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<NGUOITHAN> NGUOITHANs { get; set; }
    }
}
