//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giáo_dục_miễn_phí
    {
        public string MAKHOA { get; set; }
        public string TENKHOA { get; set; }
        public Nullable<int> NAMTL { get; set; }
        public string PHONG { get; set; }
        public string DIENTHOAI { get; set; }
        public string TRUONGKHOA { get; set; }
        public Nullable<System.DateTime> NGAYNHANCHUC { get; set; }
    }
}
