//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHOA()
        {
            this.BOMONs = new HashSet<BOMON>();
        }
    
        public string MAKHOA { get; set; }
        public string TENKHOA { get; set; }
        public Nullable<int> NAMTL { get; set; }
        public string PHONG { get; set; }
        public string DIENTHOAI { get; set; }
        public string TRUONGKHOA { get; set; }
        public Nullable<System.DateTime> NGAYNHANCHUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMON> BOMONs { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
    }
}
