//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMGIADT
    {
        public string MAGV { get; set; }
        public string MADT { get; set; }
        public int STT { get; set; }
        public Nullable<double> PHUCAP { get; set; }
        public string KETQUA { get; set; }
    
        public virtual CONGVIEC CONGVIEC { get; set; }
        public virtual GIAOVIEN GIAOVIEN { get; set; }
    }
}
